### PR TITLE
[WIP] Add basic support for a Run button

### PR DESCRIPTION
**Pull request by betatim**
Making a start on having a "run" button in commuter.

Now if you set `COMMUTER_EXECUTEPREFIX="https://localhost:8888"` or something like that a button will appear.

cc @cabhishek

### CODE REVIEW

**Comment by betatim** [comment]
The run button doesn't appear when the page is rendered on the server.

**Comment by rgbkrk** [comment]
ohhhhh Tim we moved commuter to the monorepo...

**Comment by betatim** [comment]
screen shot 2017-12-19 at 13 18 08

**Comment by rgbkrk** [comment]
Thanks for linking to that.

**Pull request closed without merging**
