### PR TITLE
Impl. GCS content provider.

### PR DESCRIPTION
**Pull request by wutali**
I added GCS content provider support Google Cloud Storage as a backend.

### CODE REVIEW

**Comment by wutali** [comment]
@mpacer Do you have any idea about my PR? If you have some feedback before the merge, I want to fix it.

**Comment by captainsafia** [comment]
@rgbkrk or @cabhishek Are any of you available to review this?

**Comment by rgbkrk** [comment]
Let's just go for it.

**Comment by rgbkrk** [comment]
At Netflix we've been running an internal version so I'm happy to see people pushing the open-source version independently.

**Pull request merged**
