### PR TITLE
Upgrades

### PR DESCRIPTION
**Pull request by rgbkrk**
I just published new packages from nteract/nteract for us, most notable changes include:

* Fix to notebook preview styling in https://github.com/nteract/nteract/pull/1682
* ~~Slimmer Plotly module (so it makes sense to use here)~~
* Removing a bunch of deprecation warnings

### CODE REVIEW

**Comment by rgbkrk** [comment]
Weird, looks like it timed out doing the production build. It's definitely the plotly dependency, though we'd have to reduce [`@nteract/plotly`](https://github.com/nteract/minimal-plotly) even more. Maybe I'll go ahead and try that now. 🤔

**Comment by lgeiger** [comment]
On CI `react-scripts` fails if webpack produces a warning:

>Failed to compile. When process.env.CI = true, warnings are treated as failures. Most CI servers set this automatically.
Critical dependencies:
7:414-421 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.

I don't know if we can customize the webpack config to silence the warning.
As a simple workaround we could unset `process.env.CI`.

**Comment by rgbkrk** [comment]
Thanks for noting that, time for me to check out the warning.

**Comment by rgbkrk** [comment]
Ha, it's the warning about plotly being a prebuilt javascript file. I'm on the right path regardless. :wink:

**Comment by rgbkrk** [comment]
Taking away Plotly for now until https://github.com/nteract/minimal-plotly/issues/4 is resolved. It's not really the size that's the issue so much as it not being commonjs.

**Comment by rgbkrk** [comment]
Good to go now!

**Comment by cabhishek** [comment]
@lgeiger Unsetting `process.env.CI` might cause `react-scripts` to run the test [watcher](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#continuous-integration) with interactive CLI.

**Pull request merged**
