### PR TITLE
Local storage

### PR DESCRIPTION
**Pull request by rgbkrk**
Don't merge, this is mostly in prototype mode. I'll certainly have to clean this up and rebase it after.

What's done and what needs doing?

* [x] "disk" service for `get`ting a file in the contents API format
* [x] express route that defers to this "disk" service for `/api/contents`
* [x] express route for a `/files/` endpoint for this
* [x] accept a baseDirectory configuration
* [x] ensure no directory traversal vulnerabilities

Flow made my life so much easier here for making sure this conformed to the API spec.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Alright, all the basics for this are setup. Now for integration work. 😄

**Comment by rgbkrk** [comment]
Here's the structure I'm expecting for a `ContentProvider`:

```
getContent(options: Options, path: string): Content
getFile(options: Options, path: string): 
```

right now I'm taking the assumption that the `options` is associated with the provider itself

**Comment by rgbkrk** [comment]
Thinking a bit more on it, the outward interface could probably be two express routers -- one for the `/files/` endpoint and one for `/api/contents/`.

**Comment by rgbkrk** [comment]
New environment variables to introduce:

```
COMMUTER_BACKEND - default to local, can also set `S3`

COMMUTER_LOCAL_DIRECTORY - what the base directory is. Defaults to `process.cwd`
```

We should probably compare and contrast with Jupyter naming so we're consistent.

**Comment by rgbkrk** [comment]
## Content Provider "spec"

a content provider exports:

```
createContentsRouter(options): Router,
createFilesRouter(options): Router,
```

The expectation is that booting this up looks like

```js
const express = require('express');
app = express();

const provider = require('someContentProvider');
const options = {}; // Assume you know the options for the provider

app.use('/api/contents/', provider.createContentsRouter(options));
app.use('/files/', provider.createFilesRouter(options));
```

**Comment by rgbkrk** [comment]
To get this all to line up better, we'll need the s3 module to not export functions that don't have a `config` and `s3` bound to them (currently a module level closure). We'll want them to return a function that accepts the options, returning a configured router (or configured s3 setup).

**Comment by rgbkrk** [comment]
Since that seems like a pretty big refactor I'd like to get this one brought in, flow setup and all. Then we'll keep iterating on making the nice interfaces.

**Comment by cabhishek** [comment]
will S3 backend work after this merge?

**Comment by rgbkrk** [comment]
> will S3 backend work after this merge?

Yeah there are zero changes to the S3 setup in this branch. This PR:

* Sets up flow typing for gradual introduction
* Lays out the pattern for content providers.

**Pull request merged**
