### PR TITLE
[Demo][No merge] create a facets component

### PR DESCRIPTION
**Pull request by rgbkrk**
This sets up a view on CSVs using the [facets visualization](https://pair-code.github.io/facets/). I'm not a fan of how I had to build and stick in static here. Could be interesting though.

screen shot 2017-07-19 at 11 15 11 am

faceting

### CODE REVIEW

**Comment by rgbkrk** [comment]
I'm leaving this for @gnestor to play with now, I won't touch this again (only prototyping).

One thing we talked about in chat was to make CSV and the data resource transform be a tabbed component that let you switch views:

```
 _______
| Table | Overview | Dive |

---------------------------
| A | B |       Happiness |
---------------------------
| 1 | 2 |             9.3 |
| 1 | 3 |             7.4 |
---------------------------
```

**Comment by gnestor** [comment]
I got some stuff to push! It looks like I don't have push access?

```
ERROR: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'https://github.com/rgbkrk/commuter.git'
```

**Comment by rgbkrk** [comment]
That's weird, let me get you set up here.

**Comment by rgbkrk** [comment]
You were already an owner on the org and "Allow edits from maintainers" is checked. Perhaps you need to use the `git` scheme rather than https?

**Comment by rgbkrk** [comment]
Added you as a collaborator explicitly to my fork just in case.

**Comment by gnestor** [comment]
It's weird, I was having this issue with [another repo](https://github.com/jupyterlab/jupyter-renderers/pull/15#issuecomment-321893106).

My remotes:

```
grant:commuter grant$ git remote -v
nteract	https://github.com/nteract/commuter.git (fetch)
nteract	https://github.com/nteract/commuter.git (push)
origin	https://github.com/gnestor/commuter.git (fetch)
origin	https://github.com/gnestor/commuter.git (push)
rgbkrk	https://github.com/rgbkrk/commuter.git (fetch)
rgbkrk	https://github.com/rgbkrk/commuter.git (push)
```

When I try to push:

```
grant:commuter grant$ git push rgbkrk HEAD:facets
ERROR: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'https://github.com/rgbkrk/commuter.git'
```

Tried using the git scheme:

```
grant:commuter grant$ git remote set-url rgbkrk git@github.com:rgbkrk/commuter.git
grant:commuter grant$ git push rgbkrk HEAD:facets
ERROR: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'git@github.com:rgbkrk/commuter.git'
```

**Comment by rgbkrk** [comment]
Have you changed your SSH keys at all? This is seeming pretty odd.

**Comment by gnestor** [comment]
Nope, just tested my keys with `ssh -T git@github.com` with great success 🤔

**Comment by gnestor** [comment]
Invite worked!

**Comment by rgbkrk** [comment]
Now that you got facets dive to work, I'm pretty tempted to ship this as part of our standard setup.

**Comment by rgbkrk** [comment]
Further work this PR needs:

* [ ] Facets component should be copied in on `prepare` (local `install`, `prepublishOnly`), rather than part of this repository
* [ ] Tab switcher needs to more closely match the rest of the style of the app
* [ ] Inline styling needs to use styled-jsx

**Comment by gnestor** [comment]
> Facets component should be copied in on prepare (local install, prepublishOnly), rather than part of this repository

Is there any reason not to do `<link rel="import" href="https://github.com/PAIR-code/facets/raw/master/facets-dist/facets-jupyter.html" />`?

> Tab switcher needs to more closely match the rest of the style of the app

Any specific suggestions?

> Inline styling needs to use styled-jsx

styled-jsx wasn't allowing me to pass dynamic values from props to style values?

**Comment by rgbkrk** [comment]
> Is there any reason not to do <link rel="import" href="https://github.com/PAIR-code/facets/raw/master/facets-dist/facets-jupyter.html" />?

The app should be able to work without being connected to the internet.

> styled-jsx wasn't allowing me to pass dynamic values from props to style values: Syntax Error: Expected `height` to not come from the closest scope.

Ah, height is fine to be a prop as is.

> > Tab switcher needs to more closely match the rest of the style of the app
> Any specific suggestions?

I _think_ we need less margin above the overall component (above the tab switcher, which is likely css from the entry stuff). The other standout to me is that the text should probably be a bit bigger on the tabs.

What would you think about a toggle like this:

image

**Comment by gnestor** [comment]
> The app should be able to work without being connected to the internet.

Ok, so we want something like`curl https://github.com/PAIR-code/facets/raw/master/facets-dist/facets-jupyter.html > static/facets-jupyter.html` in `npm publish`? Is there a cross-platform `curl`?

> Ah, height is fine to be a prop as is.

The problem is that facets-overview doesn't obey its height prop...

> What would you think about a toggle like this:

Love it 👍

**Comment by rgbkrk** [comment]
> Ok, so we want something like `curl...`

We'd only have it as a devDependency, putting in the git URL directly in the package.json (or so I assume), then `cp`'ing the file on the `prepare` directive in the npm scripts.

> The problem is that facets-overview doesn't obey its height prop...

Web components take the world by storm!!!?!?!?! ¯\\\_(ツ)\_/¯

**Comment by rgbkrk** [comment]
I'm going to go ahead and close this, as I'd like to move commuter into the nteract monorepo (assuming it doesn't turn out to be absolutely crazy). Let's revisit this as part of the transforms setup within the monorepo.

**Pull request closed without merging**
