### PR TITLE
flow type many of the components

### PR DESCRIPTION
**Pull request by rgbkrk**
Starting to flow type the frontend (thanks @lgeiger!).

### CODE REVIEW

**Comment by rgbkrk** [comment]
With flow now at the base, it seems to not be resolving node modules for the lerna packages:

```
$ npm run flow

> @nteract/commuter-lerna-base@0.1.0 flow /Users/kylek/code/src/github.com/nteract/commuter
> flow

packages/frontend/components/contents/csv.js:5
  5: import DataTransform from "@nteract/transform-dataresource";
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ @nteract/transform-dataresource. Required module not found
```

That's even though we included the flow versions of the scripts here:

```
ls packages/frontend/node_modules/@nteract/transform-dataresource/lib/
config.js                 infer.js                  virtualized-grid.js.flow
config.js.flow            infer.js.flow             virtualized-table.js
index.js                  types                     virtualized-table.js.flow
index.js.flow             virtualized-grid.js
```

**Comment by rgbkrk** [comment]
I should probably bring some base types to the top level that are shared between server and client as well (mostly contents API bits).

**Comment by rgbkrk** [comment]
This (mostly) finishes the flow typing. I ended up adding a bunch of FlowFixMes for when the `@nteract/*` modules aren't having their `*.js.flow` files picked up. Not exactly sure how to include those.

I won't touch this PR anymore (unless there's feedback I can address). All set for merge!

**Comment by lgeiger** [comment]
> With flow now at the base, it seems to not be resolving node modules for the lerna packages.

Is it because we're [ignoring the `node_modules` folder](https://github.com/nteract/commuter/blob/master/.flowconfig#L2)?

**Comment by rgbkrk** [comment]
I think so but then we run into that immutable and flow issue. :(

**Pull request merged**
