### PR TITLE
CSV time

### PR DESCRIPTION
**Pull request by rgbkrk**
I've tried out using the data resource transform in here (in a bit of a messy way). While I've gotten it to render, it looks worse than if I just mapped over and created the table at the moment. :wink:

screen shot 2017-04-13 at 6 08 25 pm

Probably need a dedicated table viewer.  ¯\\\_(ツ)\_/¯

/cc @gnestor

### CODE REVIEW

**Comment by gnestor** [comment]
You should be able to do something simpler:

```js
import React from "react";
import DataResource from "@nteract/transform-dataresource";
import csvParse from "d3-dsv";

export default function CSVView(props) {
    const data = csvParse(props.entry.content);
    return <DataResource data={data} />;
}
```

* All styles are inlined in DataResource now, so no need to import the react-virtualized stylesheet
* The schema inference is contained in DataResource, so no need to do it outside of it

**Comment by rgbkrk** [comment]
Thanks Grant! Went ahead and updated. I was including because I was running into an issue with length 

I think the styles for data resource are missing from the notebook preview stylesheets (packages/notebook-preview on nteract/nteract):

screen shot 2017-04-13 at 6 08 25 pm

Perhaps this is the first component we inline style for?

**Comment by willingc** [comment]
@rgbkrk Love the headings and spacing ;-)

**Comment by rgbkrk** [comment]
Oops, I just realized I didn't upload the GIF I recorded. I sent the PNG I already posted here. Silly me. 
table-css

**Comment by gnestor** [comment]
Hmmmm. jupyterlab_table currently does not depend on any external stylesheets:

* `virtualized-grid.js` imports `style.css`: https://github.com/gnestor/jupyterlab_table/blob/master/component/virtualized-grid.js#L8
* `style.css` doesn't contain any styles specific to react-virtualized, just fixed-data-table and vanilla-table: https://github.com/gnestor/jupyterlab_table/blob/master/component/index.css

I guess I need to clone this and debug...

**Comment by gnestor** [comment]
Update:



It looks like transform-dataresource is a little out-of-date since I adapted it for jupyterlab_table. I will update it in nteract and once a new version is released, commuter CSVs should start looking very niiiice.

Any feedback on this theme before I submit a PR to nteract?

**Comment by rgbkrk** [comment]
That's looking great! How does it look at full width?

**Comment by willingc** [comment]
Wow! Nice improvement @gnestor 👍

**Comment by gnestor** [comment]
I just updated the column width logic so now it looks nice full-width too.

**Comment by gnestor** [comment]
https://github.com/nteract/nteract/pull/1657

**Comment by rgbkrk** [comment]
I've got a local storage mode for commuter in the works here for my part in making things easier. :smile:

**Comment by rgbkrk** [comment]
Looking really good!

screen shot 2017-04-19 at 11 43 16 am

**Comment by rgbkrk** [comment]
Thanks for the data resource updates @gnestor, this is great!

**Pull request merged**
