### PR TITLE
Enable local mode

### LINKED ISSUE #87: Local Storage Backend
Right now we have an S3 backend. In order to support EFS and other NFS based storage options, we'll want another backend.

### PR DESCRIPTION
**Pull request by rgbkrk**
This does several things in service of having multiple storage backends while setting the default to local storage.

:warning: This has _one_ breaking change, which is to default us to local mode instead of S3.

* [x] Accepts env var `COMMUTER_LOCAL_STORAGE_BASEDIRECTORY`, defaulting to `process.cwd()` if not set
* [x] Accepts env var `COMMUTER_STORAGE_BACKEND` for specifying `s3` or `local`. If not set it defaults to `local`. If set to something unknown, it throws an error.
* [x] Accepts env var `COMMUTER_DISCOVERY_BACKEND`, which is slightly pointless because we only have an elasticsearch backend currently (issue for local backend in #76).
* [x] Sets up a standard for contents providers to instantiate their contents and files routers with configuration
* [x] Sets up a standard for discovery providers to instantiate their router with configuration
* [x] Switch the S3 contents provider to accept a config object instead of relying on a global singleton
* [x] Adapt tests

This closes #87.

Some additional items that would be nice-to-have:

* Many of the flow types around passed in configuration are currently `Object`. With more strong typing it will be easier to refactor these later.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Come to think of it, I should modify the Procfile for the Heroku deployment since that ships from master.

**Comment by cabhishek** [comment]
Or we could set the new ENV variable value in heroku dashboard

**Comment by rgbkrk** [comment]
One more commit about to come -- I need to handle the no-discovery-backend case.

**Comment by rgbkrk** [comment]
All set!

**Pull request merged**
